name: flutter_course_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.13.1
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.7.0
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  formz: ^0.6.1
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  path: ^1.8.3
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  sqflite: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true
